import { type Metadata } from "next";

const getSeo = (): Metadata => ({
  title: "Next Js Clean Starter Template",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
});

export default getSeo;
